format = """
[î‚¶](fg:bright-cyan)$username[ï‘„](bg:bright-cyan fg:black)$hostname[î‚´](fg:bright-cyan) \
[î‚¶](fg:bright-blue)$directory[î‚´](fg:bright-blue) \
[î‚¶](fg:green)$cmd_duration[î‚´](fg:green) \
$character \
"""

[username]
disabled = false
show_always = true
format = "[$user ]($style)"
style_user = "fg:black bg:bright-cyan"
style_root = "fg:#f38ba8 bg:bright-cyan"

[hostname]
disabled = false
ssh_only = false
ssh_symbol = "ïˆ"
format = "[ $hostname]($style)"
style = "fg:black bg:bright-cyan"
trim_at = "."

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)[ ï ]($repo_root_style)"
read_only_style = "fg:black bg:red"
repo_root_style = "fg:black bg:bright-blue"
style = "fg:black bg:bright-blue"
truncation_symbol = "â‹¯"
use_os_path_sep = true
truncation_length = 2
read_only = " â—ˆ"

[directory.substitutions]
"~/Documents" = "ïœ˜"
"~/Downloads" = "ï€™"
"~/Pictures" = "ï€¾"
"~/.config" = "ï€“"
"~/Videos" = "ï€½"
"~/Music" = "ï€"
"~/Dev" = "ó°…´ "

[fill]
symbol = " "

[cmd_duration]
format = '[ï€— $duration]($style)'
style = "fg:black bg:green"
show_milliseconds = true
min_time = 0

[character]
success_symbol = "[ğŸˆ](fg:#a6e3a1 bold)"
error_symbol = "[ğŸˆ](fr:#f38ba8 bold)"
vicmd_symbol = "[ğŸˆ](fg:#f9e2af bold)"
